### ISSUE TITLE
Connector exit status 1; not expected

### ISSUE THREAD

**Issue by rampadc** [ibm-watson-iot/connector-statsd#1]
When this connector is used in conjunction with ibm-watson-iot/grafana4iot, the connector starts and then shuts down immediately:

```
connector_1  | 2018-10-14 01:00:29,258 INFO success: statsd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
connector_1  | 2018-10-14 01:00:29,261 INFO spawned: 'connector-statsd' with pid 23
connector_1  | 2018-10-14 01:00:29,386 INFO exited: connector-statsd (exit status 1; not expected)
```
This repeats for several times until it gives up and enter FATAL state.

**Comment by durera** [comment]
There was a few issues, but I was able to reproduce this on my own setup and the recent updates in this repo got me running again.

Note there are a few changes to environment variable names (to align with names being used elsewhere) ... I've pushed an updated image to docker hub so you should be able to get this up and running now with: https://hub.docker.com/r/wiotp/connector-statsd/

```
export GRAPHITE_HOST=xxx
export GRAPHITE_PORT=xxx
export WIOTP_API_KEY=xxx
export WIOTP_API_TOKEN=xxx

docker run wiotp/connector-statsd -e WIOTP_API_KEY -e WIOTP_API_TOKEN -e GRAPHITE_HOST -e GRAPHITE_PORT
```

The grafana4iot docker-compose file has also been updated to reference the images on dockerhub now, so if you want to give that a crack that should work too:

```
export WIOTP_API_KEY=<your api key>
export WIOTP_API_TOKEN=<your auth token>
wget https://github.com/ibm-watson-iot/grafana4iot/blob/master/docker-compose.yml
docker-compose up
```
